### ISSUE TITLE
add vulcan src

### ISSUE THREAD

**Issue by eternadox** [Spinyfish/Client-Hall-Of-Fame#10]
🙏

**Comment by Spinyfish** [comment]
wait is vulcan src public now or is it still private

**Comment by eternadox** [comment]
https://github.com/TypicalModMaker/vulcan-anticheat-src-redirect

**Comment by Spinyfish** [comment]
oh someone made it public

**Comment by Spinyfish** [comment]
what a goofball

**Comment by Spinyfish** [comment]
So goofy still not adding cuz frap will dmca
