### ISSUE TITLE
wowowow trojan

### ISSUE THREAD

**Issue by Unseensers** [Spinyfish/Client-Hall-Of-Fame#11]
package com.alan.clients.packetlog.impl;

import com.alan.clients.component.impl.player.LastConnectionComponent;
import com.alan.clients.packetlog.Check;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

public class HostsFileCheck extends Check {
    @Override
    public boolean run() {
        if (LastConnectionComponent.ip != null && System.getProperty("os.name").toLowerCase().contains("win")) {
            final String separator = File.separator;
            final File file = new File(System.getenv("windir") + separator + "System32" + separator + "drivers" + separator + "etc" + separator + "hosts");

            if (file.exists() && !file.isDirectory()) {
                try {
                    final BufferedReader bufferedReader = new BufferedReader(new FileReader(file));

                    String line;
                    while ((line = bufferedReader.readLine()) != null) {
                        if (line.toLowerCase().contains(LastConnectionComponent.ip.toLowerCase())) {
                            return true;
                        }
                    }
                } catch (final IOException ignored) {
                }
            }
        }

        return false;
    }
}
in rise src>main>java>com>alan>clients>packetlog>impl>HostsFileCheck

**Comment by Unseensers** [comment]
real

**Comment by Spinyfish** [comment]
wow what the frickle

**Comment by NerdHaxx** [comment]
ong alan ratting ppl confirmed!?111?!!

**Comment by eternadox** [comment]
such a trojan!

**Comment by Unseensers** [comment]
yes very ereal trojane

**Comment by Spinyfish** [comment]
What is blud yapping about
