### ISSUE TITLE
Please add vulc** src 

### ISSUE THREAD

**Issue by Briiqn** [Spinyfish/Client-Hall-Of-Fame#12]
Hello sir, as of recent a developer (Nicholas S****), who goes by the internet alias Fre* has privatly  open sourced their anticheating plugin for spigot 1.8.x to 1.19.x entitled Vulc**. I believe it should be in this repository because of its stellar checks such as wall climb (A), Invalid (F) and much more. Furthermore its stellar combat cheat detection methods such as Autoclicker(E) also known kurtosis has changed the minecraft anticheating industry as we know it. I believe putting this wonderful and ambitious project on this  repo will better the community as a whole as it will inspire more minecraft anticheat developers to follow Fre*'s path he laid for the next generation of anticheating plugins for minecraft.

**Comment by Spinyfish** [comment]
Agasgahsgazhzhshs
