### ISSUE TITLE
Hello guys! Me again woohoo, this time selfleaking eclipse clinet !1!111!!!!

### ISSUE THREAD

**Issue by Eclipsed26** [Spinyfish/Client-Hall-Of-Fame#15]
[Download it please daddy!](https://cdn.discordapp.com/attachments/1112269292516421655/1112270515630002186/Eclipse_Client_.zip)

**Comment by Spinyfish** [comment]
blud aint know what a pull request is nahh 😭

**Comment by Eclipsed26** [comment]
> blud aint know what a pull request is nahh 😭

too lazy

**Comment by Spinyfish** [comment]
Same
