### ISSUE TITLE
Add uncp src

### ISSUE THREAD

**Issue by Briiqn** [Spinyfish/Client-Hall-Of-Fame#5]
I need to skid checks into vulcan

**Comment by Spinyfish** [comment]
Due to UNCP's heavy obfuscation it is entirely unreadable, and as it is manually obfuscated there are no transformers for it. Thus there is no point in adding UNCP source code. And in my personal opinion UNCP is likely the best anticheat out there, enterprise grade code and even better checks. Therefor it does not belong on this repository for bad source code. 

Thank you for suggestion Briiqn, but we will have to decline, good day!

**Comment by Spinyfish** [comment]
Am I safe to close this issue, or is there more you would like to add?

**Comment by Briiqn** [comment]
Can you add uncp leak then

**Comment by FluteVegetables** [comment]
UNCP has some of the best code ever. For example in “WrongTurn” class, it detects abs(pitch) > 90 AND pitch < -90. This is one of many examples of the thorough UNCP code that is very high quality.

**Comment by Spinyfish** [comment]
Yes that is intelligent, it takes advantage of how clients are more likely to abuse < -90 invalid pitch first before running the costly calculation of the absolute value of pitch. This, and many other reasons, is why we will not be adding UNCP code to the clown repo.

I have a deep respect for the UNCP devs and their revolutionary detections, optimizations, and everything else they do.

**Comment by FluteVegetables** [comment]
I agree. UNCP is very stable and detects basically any cheat such as strafe and multiaura while having 0 effect on legitimate players who want to do things like run up stairs or on slime blocks.

**Comment by Spinyfish** [comment]
I personally have to applaud the UNCP developers on their scaffold checks. IMO that was lacking the most in the original NCP, these checks use brilliant detections that have given me quite the run for my money to bypass 😅 . But I've never seen it false on a legit player, I truly don't understand how they do it.

**Comment by Briiqn** [comment]
It even detects when you walk up the stairs

**Comment by ElBeano1** [comment]
bro I got the hud bypass $$ never bans

**Comment by Spinyfish** [comment]
Shutup, you could never compare to the comedy of briiqn, your ancestors look upon you and weep for the shame you've brought to your family.

**Comment by ElBeano1** [comment]
> > bro I got the hud bypass $$ never bans
> 
> Hello siirr, you do not hbave the Hud bypass as you are using a png overlay, please stop making up bullshit has UNCP has the most premium render Hack checks such as EsP, TraceRss, ChaMS, etc, Uising a png to shopw that you are "bypassing" does not mean anyhthing as its sjust an image, please stop making fake bypasses than ky uo

sir stop the cappertion I am best at bypassertion at the esp no other client can be as good as my esp bypass even bypass on hypixel

**Comment by Briiqn** [comment]
> > > bro I got the hud bypass $$ never bans
> > 
> > Hello siirr, you do not hbave the Hud bypass as you are using a png overlay, please stop making up bullshit has UNCP has the most premium render Hack checks such as EsP, TraceRss, ChaMS, etc, Uising a png to shopw that you are "bypassing" does not mean anyhthing as its sjust an image, please stop making fake bypasses than ky uo
> 
> sir stop the cappertion I am best at bypassertion at the esp no other client can be as good as my esp bypass even bypass on hypixel 

Hllalelro sir, i am not the cpaprrring as i believee YOU are the one capwprirng, how dare you alledge i do such thing such as cpapering, iys evry offensive and rure, also id like to see your client, in this repositiory 💯💯💯🫵🙌🙌🙌🙌👋👋😝🤪😜🤪😛🤪😜😝🤣🤣🤣🤣🤣🤣🤣

**Comment by Spinyfish** [comment]
Me when a cute boy calls me “silly” aagajsagajgahsagajahajagahgs mfmfnffgfgfmmff agahagahgshagsjga
