### ISSUE TITLE
Fake Juul Src

### ISSUE THREAD

**Issue by Briiqn** [Spinyfish/Client-Hall-Of-Fame#7]
Dear sir of, 
 The juul src in this repository is not accurately correct with Juul @ juul.lol & Juul @ intent, I kindly request you remove mr nefarious's name from the code provided under nefarious/* or else we @ intent will take action and sew you for defamation of mr nefarious.
    tank you

**Comment by Spinyfish** [comment]
Dear Briiqn,

Thank you for bringing this to my attention. However, I must clarify that the information I have provided regarding the source code is correct. The Juul source code that I have uploaded on my Github repository is named "Juul" and is in no way affiliated with the Juul company or any of its products.

Furthermore, the name "Nefarious" that I have listed as the author of the code is accurate and is associated with Intent.store, which is also mentioned in the repository's description. I assure you that there is no intention of defaming Mr. Nefarious or anyone else associated with Intent.store.

If there are any specific concerns that you would like to raise, please feel free to contact me directly, and I will be happy to address them. I value your input and appreciate your efforts in bringing this to my attention.

Sincerely,

Mint Org.

**Comment by Briiqn** [comment]
Hello sir
We believe you have wrongfully (illegally) associated mr nefarious in the given code under his directory. As you can see from https://github.com/L1ncey/Juul-Client it is genetically indentical to the code found in nefarious/* we @ intent kindly request you remove mr nefarious's name from the given code or else we will sew you for defamation of our beloved nefarious.

**Comment by Briiqn** [comment]
We @ intent also would like to mention that nefarious doesnt skid tenacity, unlike this fake juul client who directly pasted render utilities from tenacity (see more here -> https://github.com/L1ncey/Juul-Client/blob/master/juul/util/render/)

**Comment by Spinyfish** [comment]
I understand your confusion sir, however this is because they also have juul src code by nefarious. Many people have released the source code publicly on github after it was leaked. Your claims of defamation are slander and if are to be continued will be punished legally.

**Comment by Briiqn** [comment]
Hello sir,
This was scientifically proven wrong as DNA evidence suggests that the source provided is not genetically identical to the Juul source provided to us by nefarious @ intent/juul . By using his name, you are ILLEGALLY attaching his name to something he did not do/create/write. Defamation in this case is defined as  " the act of communicating to a third party false statements about a person, place or thing that results in damage to its reputation." which is highly accurate about this case. We suggest you'd remove the Juul source before we @ intent will take it into our own hands.

Thanks 
             -Cedo

**Comment by Spinyfish** [comment]
Hello Mr. Cedo, it seems you are correct. The source code on this repository is incorrect. I will be leaving this up indefinitely however as I have a personal vendetta against Nefarious @ Intent. Thank you and good day.
