### ISSUE TITLE
Add mint

### ISSUE THREAD

**Issue by discord-trollering** [Spinyfish/Client-Hall-Of-Fame#9]
Mint would be a very good addition as it falls under the category of skidded clients.

**Comment by TheXNBT** [comment]
True

**Comment by Spinyfish** [comment]
![image](https://user-images.githubusercontent.com/93102482/224453970-9dac660a-835a-4f7f-99a5-467cb33c3c8b.png)

**Comment by TheXNBT** [comment]
ratio

**Comment by Spinyfish** [comment]
Ratio
